version: '3.8'
services:
  redoc:
    image: redocly/redoc
    ports:
      - 8001:80
    volumes:
      - ./docs/api/:/usr/share/nginx/html/swagger/
    environment:
      SPEC_URL: swagger/openapi.yaml
