openapi: 3.0.0
info:
  version: 1.0.0
  title: API Template
  x-logo:
    url: https://github-readme-stats.vercel.app/api/pin/?username=kawano-020&repo=api-workspace&show_owner=true&show_icons=true
  description: |
    This API is for pesonal develepments.
  
    # Introduction

    ユーザーがコンテンツ(呟き)を発信し、それに対してリプライやいいねができるサービスのAPI

    Twitterの簡易版のようなイメージ

    また、ユーザーの各アクションに対してログを作成していく

servers:
  - url: 'http://localhost:28000'

paths:
  /auth/login:
    post:
      operationId: auth.login
      tags:
        - auth
      summary: ログインする(JWTを得る)ためのAPI
      description: |
        ユーザーの`email`とHash処理前の`password`が正しい場合に対象のユーザーの`access`と`refresh`それぞれのJWTを返す。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ユーザーの`email`
                  minLength: 1
                  maxLength: 225
                password:
                  type: string
                  description: ユーザーのHash処理前の`password`
                  minLength: 1
                  maxLength: 225
              example:
                email: example@example.com
                password: user_password
      responses:
        "200":
          description: generated tokens
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tokens"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /users:
    get:
      description: |
        Returns all users
      operationId: findUsers
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tokens"
        "401":
          $ref: "#/components/responses/Unauthorized"

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        access JWT for API

        認証トークンにはJWTを使用する。
        トークンはAccessとRefreshが存在し、Authorization Headerにアクセストークンを載せた形でリクエストする。
  
        各トークンのclaimには以下を持たせる。

        - sub: ユーザーの`email`

        - exp: トークンの有効期限 (UNIX時間)

        - type: トークンの用途 (`access` | `refresh`)
  schemas:
    AccessToken:
      type: string
      description: アクセストークン
      example: "\
        eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.\
        eyJzdWIiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwiZXhwIjoiMTIzNDU2Nzg5MCIsInR5cGUiOiJhY2Nlc3MifQ.\
        3-8G0WXFGwu4Cd9Fl66AsYjBPJgtfO9CIZvdkoGW13U"
    RefreshToken:
      type: string
      description: リフレッシュトークン
      example: "\
        eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.\
        eyJzdWIiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwiZXhwIjoiMTIzNDU5ODc2MCIsInR5cGUiOiJyZWZyZXNoIn0.\
        69IVLPFVZK_rXBo2___QIETaQc4TXm7nx-mFjSz6sOY"
    Tokens:
      type: object
      properties:
        access:
          $ref: "#/components/schemas/AccessToken"
        refresh:
          $ref: "#/components/schemas/RefreshToken"
    User:
      type: "object"
      required:
        - "name"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 100
        name:
          type: "string"
          example: "Taro"
        status:
          type: "string"
          description: "user status"
          enum:
            - "pending"
            - "active"
            - "inactive"
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  responses:
    BadRequest:
      description: bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 400
            message: Error Detail(s)
    Unauthorized:
      description: unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 401
            message: Valid authentication credential lacks.
    Forbidden:
      description: forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 403
            message: Insufficient permissions to a resource.
    NotFound:
      description: not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 404
            message: The requested resource could not be found.
    InternalServerError:
      description: internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 500
            message: An unknown server error occurred internally.


security:
  - Bearer: []

tags:
  - name: auth
    description: "**認証**に関するAPI群"
