openapi: 3.0.0
info:
  version: 1.0.0
  title: API Template
  x-logo:
    url: https://github-readme-stats.vercel.app/api/pin/?username=kawano-020&repo=api-workspace&show_owner=true&show_icons=true
  description: |
    This API is for pesonal develepments.
  
    # Introduction

    ユーザーがコンテンツ(呟き)を発信し、それに対してリプライやいいねができるサービスのAPI

    Twitterの簡易版のようなイメージ

    また、ユーザーの各アクションに対してログを作成していく
  contact:
    name: MyGithub
    url: https://github.com/kawano-020

servers:
  - url: 'http://localhost:28000'

paths:
  $ref: './paths/index.yaml'

components:
  securitySchemes:
    $ref: "./components/securitySchemes/index.yaml"
  parameters:
    $ref: "./components/parameters/index.yaml"
  schemas:
    $ref: "./components/schemas/index.yaml"
  responses:
    $ref: "./components/responses/index.yaml"

security:
  - Bearer: []

tags:
  - name: auth
    description: "**認証**に関するAPI群"
  - name: user
    description: "**ユーザー**に関するAPI群"
  - name: content
    description: |
      **コンテンツ**に関するAPI群

      コンテンツは基本的に`updated_at`の降順とする
