name: "Deploy Github Pages"

on:
  push:
    branches:
      - main

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      
      - name: Set up Swagger CLI
        run: npm install -g swagger-cli
      
      - name: Set up Redoc CLI
        run: npm install -g redoc-cli
      
      - name: Generate Redoc HTML
        run: npm run generate-redoc

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build:prd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
